apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-deployment
  labels:
    app: mytomcat
spec:
  replicas: 7
  selector:
    matchLabels:
      app: mytomcat
  template:
    metadata:
      labels:
        app: mytomcat
    spec:
      containers:
      - name: argocd-deployment
        image: eshhuba/mytomcat:latest
        ports:
        - containerPort: 8080

